version: '3'
services:
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging: 
      driver: "none"
  api:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - db_mongo
  web_client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - api