version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
  web_client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - api