module.exports = {
    ROOM_STATE: Object.freeze({
        EMPTY: 'EMPTY', 
        INVALID: 'INVALID', 
        VALID: 'VALID'
    }),
    GAME_STAGE: Object.freeze({
        WAITING_FOR_PLAYERS: 'WAITING_FOR_PLAYERS',
        WAITING_TO_START: 'WAITING_TO_START',
        SELECTING_BASELINE_PLAYER: 'SELECTING_BASELINE_PLAYER',
        BASELINE_PLAYER_RECORDING: 'BASELINE_PLAYER_RECORDING',
        OTHER_PLAYERS_LISTENING_TO_BASELINE: 'OTHER_PLAYERS_LISTENING_TO_BASELINE',
        OTHER_PLAYERS_RECORDING: 'OTHER_PLAYERS_RECORDING',
        FINAL_RECORDING_DONE: 'FINAL_RECORDING_DONE'
    })
}